/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VUE;

import core.Agent;
import core.Contact;
import core.Enseignant;
import core.Etudiant;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MAXETTE
 */
public class Contact_Creation extends javax.swing.JFrame {
private Connection connection;
    /**
     * Creates new form Contact_Creation
     */
    public Contact_Creation() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TEXT_Nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TEXT_Date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TEXT_Address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TEXT_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TEXT_TelNumber = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TEXT_Code = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TEXT_Cycle = new javax.swing.JTextField();
        TEXT_Niveau = new javax.swing.JTextField();
        BUT_CREER_Etudiant = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TEXT_statut_Enseignant = new javax.swing.JTextField();
        BUT_CREER_Enseigant = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TEXT_Salaire = new javax.swing.JTextField();
        TEXT_satatut_Agent = new javax.swing.JTextField();
        TEXT_Categorie = new javax.swing.JTextField();
        TEXT_Indicesalaire = new javax.swing.JTextField();
        TEXT_Occupation = new javax.swing.JTextField();
        BUT_CEERAGENT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Creation");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Informations_de_base");

        jLabel3.setText("Nom");

        jLabel4.setText("Date");

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        jLabel7.setText("TelNumber");

        jLabel19.setText("Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXT_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(TEXT_Date)
                            .addComponent(TEXT_Address))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXT_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(TEXT_TelNumber)
                            .addComponent(TEXT_Code))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TEXT_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TEXT_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TEXT_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TEXT_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TEXT_TelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEXT_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setText("      ETUDIANT");

        jLabel9.setText("Cycle");

        jLabel10.setText("Niveau");

        BUT_CREER_Etudiant.setBackground(new java.awt.Color(0, 153, 255));
        BUT_CREER_Etudiant.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        BUT_CREER_Etudiant.setText("CREER(Etudiant)");
        BUT_CREER_Etudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_CREER_EtudiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEXT_Cycle)
                            .addComponent(TEXT_Niveau, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(BUT_CREER_Etudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TEXT_Cycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TEXT_Niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BUT_CREER_Etudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel11.setText("       ENSEIGNANT");

        jLabel12.setText("Statut");

        BUT_CREER_Enseigant.setBackground(new java.awt.Color(0, 153, 255));
        BUT_CREER_Enseigant.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        BUT_CREER_Enseigant.setText("CREER(Enseignant)");
        BUT_CREER_Enseigant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_CREER_EnseigantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(TEXT_statut_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUT_CREER_Enseigant, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TEXT_statut_Enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(BUT_CREER_Enseigant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("           AGENT");

        jLabel14.setText("Salaire");

        jLabel15.setText("Statut");

        jLabel16.setText("Categorie");

        jLabel17.setText("IndiceSalaire");

        jLabel18.setText("Occupation");

        BUT_CEERAGENT.setBackground(new java.awt.Color(0, 153, 255));
        BUT_CEERAGENT.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        BUT_CEERAGENT.setText("CREER(Agent)");
        BUT_CEERAGENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_CEERAGENTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TEXT_Categorie, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(TEXT_Salaire)
                                    .addComponent(TEXT_satatut_Agent)
                                    .addComponent(TEXT_Indicesalaire)
                                    .addComponent(TEXT_Occupation))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(BUT_CEERAGENT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TEXT_Salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(TEXT_satatut_Agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(TEXT_Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TEXT_Indicesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TEXT_Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(BUT_CEERAGENT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(265, 265, 265))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUT_CREER_EtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_CREER_EtudiantActionPerformed
        // TODO add your handling code here:
      try {
    int code = Integer.parseInt(TEXT_Code.getText());
    String nom_saisi = TEXT_Nom.getText();
    String Date_Nais = TEXT_Date.getText();
    
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    Date dateNaissance = format.parse(Date_Nais);
    java.sql.Date sqlDateNaissance = new java.sql.Date(dateNaissance.getTime());
    
    String adress = TEXT_Address.getText();
    String email = TEXT_Email.getText();
    int Tel = Integer.parseInt(TEXT_TelNumber.getText());
    String cycle = TEXT_Cycle.getText();
    int Niveau = Integer.parseInt(TEXT_Niveau.getText());
    
    // Vérifier si tous les champs sont non nuls
    if (code == 0 || nom_saisi.isEmpty() || Date_Nais.isEmpty() || adress.isEmpty() || email.isEmpty() || cycle.isEmpty()) {
        throw new IllegalArgumentException("Tous les champs doivent être renseignés.");
    }
    
    Etudiant C  = new Etudiant(code,nom_saisi,sqlDateNaissance,adress,email,Tel,cycle,Niveau);
    C.insererDansBaseDeDonnees();
    JOptionPane.showMessageDialog(null, "ENREGISTREMENT EFFECTUE....");
} catch (NumberFormatException e) {
    // Gérer l'exception lorsque la conversion en entier échoue
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (ParseException e) {
    // Gérer l'exception lorsque la conversion de la date échoue
    e.printStackTrace();JOptionPane.showMessageDialog(null, "ENREGSITREMENT ENTRAVE....");
} catch (SQLException e) {
    // Gérer l'exception liée à l'interaction avec la base de données
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (IllegalArgumentException e) {
    // Gérer l'exception lorsque tous les champs ne sont pas renseignés
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
}

        
           
    }//GEN-LAST:event_BUT_CREER_EtudiantActionPerformed

    
    private void BUT_CREER_EnseigantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_CREER_EnseigantActionPerformed
        // TODO add your handling code here:
        try {
    int code = Integer.parseInt(TEXT_Code.getText());
    String nom_saisi = TEXT_Nom.getText();
    String Date_Nais = TEXT_Date.getText();

    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    Date dateNaissance = null;
    try {
        dateNaissance = format.parse(Date_Nais);
    } catch (ParseException ex) {
        Logger.getLogger(Contact_Creation.class.getName()).log(Level.SEVERE, null, ex);
    }
    java.sql.Date sqlDateNaissance = new java.sql.Date(dateNaissance.getTime());

    String adress = TEXT_Address.getText();
    String email = TEXT_Email.getText();
    int Tel = Integer.parseInt(TEXT_TelNumber.getText());
    String statut = TEXT_statut_Enseignant.getText();

    // Vérifier si tous les champs sont non nuls
    if (code == 0 || nom_saisi.isEmpty() || Date_Nais.isEmpty() || adress.isEmpty() || email.isEmpty() || statut.isEmpty()) {
        throw new IllegalArgumentException("Tous les champs doivent être renseignés.");
    }

    Enseignant C = new Enseignant(code, nom_saisi, sqlDateNaissance, adress, email, Tel, statut);

    C.insererDansBaseDeDonnees();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT EFFECTUE....");
} catch (NumberFormatException e) {
    // Gérer l'exception lorsque la conversion en entier échoue
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (SQLException e) {
    // Gérer l'exception liée à l'interaction avec la base de données
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (IllegalArgumentException e) {
    // Gérer l'exception lorsque tous les champs ne sont pas renseignés
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
}

    }//GEN-LAST:event_BUT_CREER_EnseigantActionPerformed

    private void BUT_CEERAGENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_CEERAGENTActionPerformed
        // TODO add your handling code here:
        try {
    int code = Integer.parseInt(TEXT_Code.getText());
    String nom_saisi = TEXT_Nom.getText();
    String Date_Nais = TEXT_Date.getText();

    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    Date dateNaissance = null;
    try {
        dateNaissance = format.parse(Date_Nais);
    } catch (ParseException ex) {
        Logger.getLogger(Contact_Creation.class.getName()).log(Level.SEVERE, null, ex);
    }
    java.sql.Date sqlDateNaissance = new java.sql.Date(dateNaissance.getTime());

    String adress = TEXT_Address.getText();
    String email = TEXT_Email.getText();
    int Tel = Integer.parseInt(TEXT_TelNumber.getText());

    double salaire = Double.parseDouble(TEXT_Salaire.getText());
    String statut = TEXT_satatut_Agent.getText();
    int IndiceSalaire = Integer.parseInt(TEXT_Indicesalaire.getText());
    String categorie = TEXT_Categorie.getText();
    String occupation = TEXT_Occupation.getText();

    // Vérifier si tous les champs sont non nuls
    if (code == 0 || nom_saisi.isEmpty() || Date_Nais.isEmpty() || adress.isEmpty() || email.isEmpty() || statut.isEmpty() || categorie.isEmpty() || occupation.isEmpty()) {
        throw new IllegalArgumentException("Tous les champs doivent être renseignés.");
    }

    Agent C = new Agent(code, nom_saisi, sqlDateNaissance, adress, email, Tel, salaire, statut, categorie, IndiceSalaire, occupation);

    C.insererDansBaseDeDonnees();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT EFFECTUE....");
} catch (NumberFormatException e) {
    // Gérer l'exception lorsque la conversion en entier ou double échoue
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (SQLException e) {
    // Gérer l'exception liée à l'interaction avec la base de données
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
} catch (IllegalArgumentException e) {
    // Gérer l'exception lorsque tous les champs ne sont pas renseignés
    e.printStackTrace();
     JOptionPane.showMessageDialog(null, "ENREGISTREMENT ENTRAVE....");
}

    }//GEN-LAST:event_BUT_CEERAGENTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 try{
        /* Create and display the form */
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/contacts", "root", "");
        
        // Affichage d'un message de confirmation si la connexion a réussi
        JOptionPane.showMessageDialog(null, "La connexion à la base de données a été établie avec succès.");

        // Création et affichage de la fenêtre principale de l'application
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Contact_Creation frame = new Contact_Creation();
            frame.setVisible(true);
            }
        });
    } catch (SQLException e) {
        // Gestion des exceptions en cas d'échec de la connexion
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Une erreur est survenue lors de la connexion à la base de données : " + e.getMessage());
    }// Initialisez votre connexion ici
    
    /* Votre code pour initialiser la connexion */
    
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUT_CEERAGENT;
    private javax.swing.JButton BUT_CREER_Enseigant;
    private javax.swing.JButton BUT_CREER_Etudiant;
    private javax.swing.JTextField TEXT_Address;
    private javax.swing.JTextField TEXT_Categorie;
    private javax.swing.JTextField TEXT_Code;
    private javax.swing.JTextField TEXT_Cycle;
    private javax.swing.JTextField TEXT_Date;
    private javax.swing.JTextField TEXT_Email;
    private javax.swing.JTextField TEXT_Indicesalaire;
    private javax.swing.JTextField TEXT_Niveau;
    private javax.swing.JTextField TEXT_Nom;
    private javax.swing.JTextField TEXT_Occupation;
    private javax.swing.JTextField TEXT_Salaire;
    private javax.swing.JTextField TEXT_TelNumber;
    private javax.swing.JTextField TEXT_satatut_Agent;
    private javax.swing.JTextField TEXT_statut_Enseignant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
