/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VUE;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MAXETTE
 */
public class MainFrmApplication extends javax.swing.JFrame {
     private Connection connection;
    /**
     * Creates new form MainFrmApplication
     */
    public MainFrmApplication() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BUT_CREATION_CONTACT = new javax.swing.JButton();
        BUT_LISTE_CONTACT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("            BIENVENUE");

        BUT_CREATION_CONTACT.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        BUT_CREATION_CONTACT.setText("CREATION_CONTACT");
        BUT_CREATION_CONTACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_CREATION_CONTACTActionPerformed(evt);
            }
        });

        BUT_LISTE_CONTACT.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        BUT_LISTE_CONTACT.setText("LISTE_CONTACT");
        BUT_LISTE_CONTACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_LISTE_CONTACTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BUT_CREATION_CONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BUT_LISTE_CONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUT_CREATION_CONTACT)
                    .addComponent(BUT_LISTE_CONTACT))
                .addGap(145, 145, 145))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUT_CREATION_CONTACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_CREATION_CONTACTActionPerformed
        // TODO add your handling code here:
        Contact_Creation createContactFrame = new Contact_Creation();
                createContactFrame.setVisible(true);
    }//GEN-LAST:event_BUT_CREATION_CONTACTActionPerformed

    private void BUT_LISTE_CONTACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_LISTE_CONTACTActionPerformed
        // TODO add your handling code here:
        Liste_Contact ListeContact= new Liste_Contact();
         ListeContact.setVisible(true);
        
        
    }//GEN-LAST:event_BUT_LISTE_CONTACTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrmApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     try{
        /* Create and display the form */
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/contacts", "root", "");
        
        // Affichage d'un message de confirmation si la connexion a réussi
        JOptionPane.showMessageDialog(null, "La connexion à la base de données a été établie avec succès.");

        // Création et affichage de la fenêtre principale de l'application
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrmApplication().setVisible(true);
            }
        });
    } catch (SQLException e) {
        // Gestion des exceptions en cas d'échec de la connexion
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Une erreur est survenue lors de la connexion à la base de données : " + e.getMessage());
    }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUT_CREATION_CONTACT;
    private javax.swing.JButton BUT_LISTE_CONTACT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
